// Root
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";

// Auth module
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const CREATE_TEMPORARY_ADDRESS = "CREATE_TEMPORARY_ADDRESS";
export const REPLACE_TEMPORARY_ADDRESS = "REPLACE_TEMPORARY_ADDRESS";

// Builder module
export const SET_DOUGH = "SET_DOUGH";
export const SET_SIZE = "SET_SIZE";
export const SET_SAUCE = "SET_SAUCE";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const DROP_INGREDIENT = "DROP_INGREDIENT";
export const SET_NAME = "SET_NAME";

// Cart module
export const ADD_PIZZA = "ADD_PIZZA";
export const UPDATE_PIZZA_QUANTITY = "UPDATE_PIZZA_QUANTITY";
export const UPDATE_MISC_QUANTITY = "UPDATE_MISC_QUANTITY";
export const UPDATE_PIZZA_PRICES = "UPDATE_PIZZA_PRICES";
export const SET_USER_ID_TO_CART_ORDER = "SET_USER_ID_TO_CART_ORDER";
export const SETUP_EXIST_ORDER = "SETUP_EXIST_ORDER";
export const RESET_STATE = "RESET_STATE";
